### ISSUE TITLE
Cadastro de empresa

### ISSUE THREAD

**Issue by JulioCesarAlvess** [muralis-labs/jane-portal#46]
- [x] criar input para cadastro de empresa

- esse input só aparece para cadastro de pessoa jurídica
- esse input é um select com um botão da frente:

![Image](https://github.com/muralis-labs/jane-portal/assets/60191656/411817a7-a14f-410a-b25d-2d9d30ca91ad)

- não vamos colocar a lupa por enquanto (analisar esforço - o alguns inputs têm startAdornment e endAdornment, se der para utilizar, colocamos, se não, deixamos para depois)

- [x] criar contexto para cadastro de empresa
- [x] adicionar hook de consulta de empresas (adicionar slateTime igual a consulta de colaboradores)
- [x] alterar a lógica para acessar a tela de cadastro:
   1. quando selecionado contrato terceiro deve exibir o componente de empresa;
- [x] alterar a lógica para acessar a tela de atualização:
   1. quando formos passar da tela de listagem para a tela de atualização vamos passar o tipo de contrato na url e o id da empresa;
   2. ao chegar na tela de atualização está consultando no endpoint "/v1/colaboradores/${id}", esse endpoint é o endpoint genérico, nós vamos alterar para consultar os colaboradores por tipo, então se o tipo for contrato direto vamos consultar no físico e se for contrato terceito consultar no jurídico.
   3. ao carregar a tela de atualização, quando for do tipo terceiro deve exibir o input;
   4. ao consultar um colaborador do tipo terceiro e ter uma empresa, deve setar como selecionado.
- [x] adicionar a lista de empresa buscada no input
- [x] adicionar modal de cadastro de empresa (o input data-inicial -> data-final não existe, vamos fazer com dois inputs de data, depois a gente cria esse novo input):

![Image](https://github.com/muralis-labs/jane-portal/assets/60191656/282c879b-0ebf-4814-b952-4ff2cc2d8692)

- [x] adicinar hook de cadastro de empresa

**Comment by decioneto** [comment]
Aguardando o pr que adiciona o tipo do colaborador no get de colaboradores/${id}

**Comment by JulioCesarAlvess** [comment]
branch feature: feature/cadastro-empresa
